a = input('digite algo:')
print('o tipo primitivo é ',type(a))
print('só tem espaços?',a.isspace())
print('isso é um valor númerico?',a.isnumeric())
print('isso é alfaetico?',a.isalpha())
print('isso é alfa numerico?',a.isalnum())
print('esta em maiuscula?', a.isupper())
print('esta em minuscula?', a.islower())
print('está capitalizada?',a.istitle())